services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: figma-nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  # Для разработки - dev версия
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: figma-nextjs-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: