# Dockerfile для разработки
FROM node:18-slim

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Копирование исходного кода
COPY . .

EXPOSE 3000

# Запуск в режиме разработки
CMD ["npm", "run", "dev"]